USE master;
GO
ALTER DATABASE WebProgrammingSecurity SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE WebProgrammingSecurity;
GO
CREATE DATABASE WebProgrammingSecurity;
GO

USE WebProgrammingSecurity;
GO
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
GO
CREATE TABLE roles (
	id BIGINT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE users (
	id BIGINT IDENTITY(1,1) PRIMARY KEY,
	username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(150) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	full_name NVARCHAR(200) NULL,
	images VARCHAR(500) NULL,
	enabled BIT NOT NULL,
	role_id BIGINT NOT NULL,
	CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);
GO